beam:
  admin:
    swagger-open: true  #是否开启swagger (true/false)
    kaptcha-open: false
    redis-open: false  # 是否开启redis缓存  true开启   false关闭
    shiro-redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
    version: 0.0.1
server:
   port: 8082
   #servlet:
     #context-path: /public_welfare
spring:
  profiles:
    active: @spring.active@


log:
  path: beam-admin-logs
---

spring:
  profiles: local
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #本地
      #url: jdbc:mysql://192.168.0.188:3306/public_welfare?serverTimezone=GMT%2B8&useUnicode=true&useSSL=true
      #服务器
      url: jdbc:mysql://39.97.237.246:3306/public_welfare?serverTimezone=GMT%2B8&useUnicode=true&useSSL=true
      username: root
      password: root
      filters: log4j,wall,mergeStat
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:      # 密码（默认为空）
#    timeout: 6000ms  # 连接超时时长（毫秒）
## 博客 https://www.jianshu.com/p/e1df915f0125
#dubbo:
#  scan:
#    basePackages: com.hsshy.beam.modular.*.service
#  application:
#    id: beam-admin
#    name: beam-admin
#    qos-enable: true
#    qos-port: 33333
#  protocol:
#    id: dubbo
#    name: dubbo
#    port: 20880
#    status: server
#  registry:
#    id: my-registry
#    address: zookeeper://119.29.192.127:2181
#    timeout: 100000

---

#spring:
 # profiles: dev
 # datasource:
  #  url: jdbc:mysql://192.168.0.188:3306/erp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
  #  username: root
  #  password: root
   # filters: log4j,wall,mergeStat
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password:      # 密码（默认为空）
#    timeout: 6000ms  # 连接超时时长（毫秒）

---


#spring:
  #profiles: produce
 # datasource:
  #  url: jdbc:mysql://192.168.0.188:3306/erp?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
  #  username: root
  #  password: root
 #   filters: log4j,wall,mergeStat
#  redis:
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: Wwzt1EwP/UpUA     # 密码（默认为空）
#    timeout: 6000ms  # 连接超时时长（毫秒）